--
-- This script creates a table for brackets
--
-- Usage: psql -U eek2138 -h w4111a.eastus.cloudapp.azure.com proj1part2 < tables/004-players.psql
--

CREATE TABLE Players(
    p_id SERIAL,
    first_name VARCHAR(40),
    last_name VARCHAR(40),
    rank SMALLINT,
    birth DATE NULL,
    country VARCHAR(40) NOT NULL,
    PRIMARY KEY (p_id),
    FOREIGN KEY (country) REFERENCES Countries(name) ON DELETE NO ACTION
);
