--
-- This script creates a table for brackets
--
-- Usage: psql -U eek2138 -h w4111a.eastus.cloudapp.azure.com proj1part2 < tables/007-placed_in.psql
--

CREATE TABLE Placed_In(
    player_id INTEGER,
    bracket INTEGER,
    round VARCHAR(3),
    round_number SMALLINT,
    PRIMARY KEY (bracket, player_id),
    FOREIGN KEY (player_id) REFERENCES Players(p_id)
        ON DELETE NO ACTION,
    FOREIGN KEY (bracket) REFERENCES Brackets(b_id)
        ON DELETE CASCADE
);
